
class AppStrings {
  static String appname = "Doctime",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here....",
      fullname = "Full Name",
      fullnameHint = "Enter your name here..",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password?",
      login = "Login",
      signup = "Signup",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      welcome = "Welcome",
      search = "Search Doctor",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney",
      changepassword = "Change Password",
      termCondi = "Term & Conditions",
      signout = "Signout";
}

